name: tld
channels:
  - pytorch
  - conda-forge

dependencies:
  - cudatoolkit=11.3
  - datasets=1.18.3
  - ipywidgets=
  - jupyterlab=3.2.8
  - numpy=1.22.1
  - pandas=1.4.0
  - python=3.9.10
  - pytorch=1.10.2
  - scikit-learn=1.0.2
  - torchaudio=0.10.2
  - torchvision=0.11.3
  - tqdm=4.62.3
  - transformers=4.12.2
